apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: sameersbn/nextcloud:18.0.2
      args: ["app:nginx"]
      env:
        - name: NEXTCLOUD_URL
          value: http://cloud.example.com

        - name: NEXTCLOUD_PHP_FPM_HOST
          value: nextcloud
        - name: NEXTCLOUD_PHP_FPM_PORT
          value: "9000"

      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 1
